language: python
python:
  - 3.9
git:
  depth: false
install:
  - pip install coveralls PyYAML coveralls
  - pip install -r requirements.txt
  - sudo apt-get install -y texlive-latex-recommended
script:
  - coverage run download_data.py
  - coverage run process_data.py
  - coverage run fold_data.py
  - coverage run describe_data.py
branches:
  only:
    - master
notifications:
  email: false
after_sucess:
  - coveralls
